trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: "runBuild"
        steps:
        - script: echo Build
        displayName: 'Build'
  - stage: Test
    displayName: Test
    jobs:
        - job: 'j2'
          steps:
          - script: echo Test
          displayName: 'Test'
  - stage: Security
    displayName: SecurityScan
    jobs:
      - job: 'scan'
        steps:
        - script: echo SecurityScan
          displayName: 'SecurityScan'
